// ESLint v9 flat config
export default [
  {
    files: ["src/**/*.js"],
    languageOptions: {
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        console: "readonly",
        alert: "readonly",
        confirm: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        fetch: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        URL: "readonly",
        MouseEvent: "readonly",
        Event: "readonly",
        Math: "readonly",
        JSON: "readonly",
        Object: "readonly",
        Array: "readonly",
        String: "readonly",
        Number: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        isNaN: "readonly",
        isFinite: "readonly",
        RegExp: "readonly",
        Error: "readonly",
        Node: "readonly",
        HTMLTextAreaElement: "readonly",
        performance: "readonly",
        requestAnimationFrame: "readonly",
      },
      ecmaVersion: 2022,
    },
    rules: {
      "no-unused-vars": ["warn", { "args": "none", "varsIgnorePattern": "^_" }],
      "no-undef": "error",
      "no-console": "off",
    },
  },
];
